name: Build and deploy Node.js app to Azure Web App - NFRD-Web

on:
  push:
    branches:
      - NFRD-31-web
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: npm install, build, and test for backend
        run: |
          cd webapp/backend
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: npm install, build, and test for frontend
        run: |
          cd webapp/frontend
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip backend artifact for deployment
        run: zip -r backend-release.zip webapp/backend/*

      - name: Zip frontend artifact for deployment
        run: zip -r frontend-release.zip webapp/frontend/*

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: backend-app
          path: backend-release.zip

      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: frontend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend-app

      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: frontend-app

      - name: Unzip backend artifact for deployment
        run: unzip -o backend-release.zip -d backend

      - name: Unzip frontend artifact for deployment
        run: unzip -o frontend-release.zip -d frontend

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy backend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NFRD-Web'
          slot-name: 'Production'
          package: backend

      - name: 'Deploy frontend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NFRD-Web'
          slot-name: 'Production'
          package: frontend
